name: deploy
on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 194.87.252.63
          username: root
          password: BUqs,ARN{PH5
          script: |
            cd autoservice-manager
            git pull

      - name: stop services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 194.87.252.63
          username: root
          password: BUqs,ARN{PH5
          script: |
            cd autoservice-manager
            docker compose stop frontend backend
            docker rm backend_service
            docker rm frontend_service
            docker rmi autoservice-manager/backend
            docker rmi autoservice-manager-frontend

      - name: build and run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 194.87.252.63
          username: root
          password: BUqs,ARN{PH5
          script: |
            cd autoservice-manager
            gradle -p backend/ jibDockerBuild
            docker compose build
            docker compose up -d
