name: deploy
on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{  secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd autoservice-manager
            git pull

      - name: stop services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{  secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd autoservice-manager
            docker stop frontend_service backend_service reverse_proxy
            docker rm backend_service
            docker rm frontend_service
            docker rm reverse_proxy
            docker rmi autoservice-manager/backend
            docker rmi autoservice-manager-frontend
            docker rmi nginx

      - name: build and run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{  secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd autoservice-manager
            gradle -p backend/ jibDockerBuild
            docker compose -f docker-compose.yml -f docker-compose.prod.yml build
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
